const items = [
    
    {
        id: '001',
        image: 'myntraimage/earring1.jpg',
        company: 'Carlton London',
        item_name: 'Rhodium-Plated CZ Floral Studs',
        original_price: 1045,
        current_price: 606,
        discount: 42,
        return_period: 14,
        delivery_date: 'within 6 days',
        rating: {
            stars: 4.5,
            count: 1400,
        },
    },
    
    {
        id: '002',
        image: 'myntraimage/lehenga1.jpg',
        company: 'NUEVOSDAMAS',
        item_name: 'Women Red & White Printed A-Line Knee-Length Skirts',
        original_price: 1599,
        current_price: 495,
        discount: 69,
        return_period: 14,
        delivery_date: 'within 10 days',
        rating: {
            stars: 4.1,
            count: 249,
        },
    },
    {
        id: '003',
        image: 'myntraimage/jersy1.jpg',
        company: 'ADIDAS',
        item_name: 'Indian Cricket ODI Jersey',
        original_price: 999,
        current_price: 999,
        discount: 0,
        return_period: 14,
        delivery_date: 'within 6 days',
        rating: {
            stars: 5.0,
            count: 10,
        },
    },
    {
        id: '004',
        image: 'myntraimage/Bdress1.jpg',
        company: 'Roadster',
        item_name: 'Pure Cotton T-shirt',
        original_price: 1399,
        current_price: 489,
        discount: 65,
        return_period: 14,
        delivery_date: 'within 6 days',
        rating: {
            stars: 4.2,
            count: 3500,
        },
    },
    {
        id: '005',
        image: 'myntraimage/shoes1.jpg',
        company: 'Nike',
        item_name: 'Men ReactX Running Shoes',
        original_price: 14995,
        current_price: 14995,
        discount: 0,
        return_period: 14,
        delivery_date: 'Within 10 days',
        rating: {
            stars: 0.0,
            count: 0,
        },
    },
    {
        id: '006',
        image: 'myntraimage/halfpant1.jpg',
        company: 'The Indian Garage Co',
        item_name: 'Men Slim Fit Regular Shorts',
        original_price: 1599,
        current_price: 639,
        discount: 60,
        return_period: 14,
        delivery_date: 'Tomorrow',
        rating: {
            stars: 4.2,
            count: 388,
        },
    },
    {
        id: '007',
        image: 'myntraimage/perfume1.jpg',
        company: 'Nivea',
        item_name: 'Men Fresh Deodrant 150ml',
        original_price: 285,
        current_price: 142,
        discount: 50,
        return_period: 14,
        delivery_date: 'Within 5 days',
        rating: {
            stars: 4.2,
            count: 5200,
        },
    },
    {
        id: '008',
        image: 'myntraimage/dress1.jpg',
        company: 'CUKOO',
        item_name: 'Women Padded Halter Neck Swimming Dress',
        original_price: 2599,
        current_price: 1507,
        discount: 42,
        return_period: 14,
        delivery_date: 'Tomorrow',
        rating: {
            stars: 4.3,
            count: 24,
        },
    },

    {
        id: '009',
        image: 'myntraimage/shirt.jpg',
        company: 'LUIS',
        item_name: 'luis cotton whitish full shirt',
        original_price: 1399,
        current_price: 797,
        discount: 43,
        return_period: 10,
        delivery_date: 'within 6 days',
        rating: {
            stars: 4.3,
            count: 3944,
        },
    }
];